### ISSUE TITLE
Yarn error running the server bundle

### ISSUE THREAD

**Issue by unRARed** [SpinalCMS/bridgetown-docs-template#5]
I'm new to `bridgetown`, so hopefully this is just a simple misconfiguration. I've used both `nanoc` and `middleman` in the past though, so I'm not new to ruby static site builders. Seems like bridgetown is trying to load an npm package for this template and failing per the error: `error Error: https://registry.yarnpkg.com/bridgetown-docs-template: Not found`

Here's the full trace:

```shell
➜ bin/bridgetown start                                      
[Bridgetown]           Starting: Bridgetown v1.3.1 (codename "Kelly Butte")
[Server] * Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
[Server] * PID: 28842
yarn add v1.22.21
[1/4] 🔍  Resolving packages...
yarn add v1.22.21
[1/4] 🔍  Resolving packages...
error Error: https://registry.yarnpkg.com/bridgetown-docs-template: Not found
    at params.callback [as _callback] (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:66148:18)
    at self.callback (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:140874:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:141846:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:141768:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Error: https://registry.yarnpkg.com/bridgetown-docs-template: Not found
    at params.callback [as _callback] (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:66148:18)
    at self.callback (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:140874:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:141846:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:141768:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[Bridgetown]                SSR: enabled.
[Server] * Listening on http://0.0.0.0:3000
[Server] Use Ctrl-C to stop
[Frontend] touch frontend/styles/jit-refresh.css
[Frontend] yarn run esbuild-dev
[Frontend] yarn run v1.22.21
[Frontend] $ node esbuild.config.js --watch
[Frontend] esbuild: frontend bundling started...
[Frontend] esbuild: frontend bundling complete!
[Frontend] esbuild: entrypoints processed:
[Frontend]          - index.NS2NXCKO.js: 153B
[Frontend]          - index.XTB3LF4F.css: 10.75KB
[Bridgetown]        Environment: development
[Bridgetown]             Source: /Users/unrared/Repos/rift-tips/src
[Bridgetown]        Destination: /Users/unrared/Repos/rift-tips/output
[Bridgetown]     Custom Plugins: /Users/unrared/Repos/rift-tips/plugins
[Bridgetown]         Generating… 
[Bridgetown]         Pagination: disabled. Enable in site config with pagination:\n enabled: true
[Bridgetown]             Done! 🎉 Completed in less than 0.2 seconds.
[Bridgetown]                     
[Bridgetown]     Now serving at: http://localhost:3000
[Bridgetown]                     http://192.168.1.236:3000
[Bridgetown]                     
[Server] 127.0.0.1 - - [28/Dec/2023:10:42:42 -0800] "GET / HTTP/1.1" 200 9142 0.0002
[Server] 127.0.0.1 - - [28/Dec/2023:10:42:42 -0800] "GET / HTTP/1.1" 200 9142 0.0002
[Server] 127.0.0.1 - - [28/Dec/2023:10:42:42 -0800] "GET /_bridgetown/static/index.NS2NXCKO.js HTTP/1.1" 200 153 0.0006
[Server] 127.0.0.1 - - [28/Dec/2023:10:42:42 -0800] "GET /_bridgetown/static/index.XTB3LF4F.css HTTP/1.1" 200 11012 0.0011
[Server] 127.0.0.1 - - [28/Dec/2023:10:42:42 -0800] "GET /images/logo.svg HTTP/1.1" 304 - 0.0002
[Server] 127.0.0.1 - - [28/Dec/2023:10:42:42 -0800] "GET /favicon.ico HTTP/1.1" 304 - 0.0003
```

Any ideas? My code is on Github from https://github.com/unRARed/rift-tips. Thanks for your help!

**Comment by crespire** [comment]
Were you able to figure this out? I'm getting the same error, though I was able to remove the yarn error by removing `yarn.lock` - `npm` errors out with the same 404.

**Comment by unRARed** [comment]
It seems to [stem from this](https://github.com/SpinalCMS/bridgetown-docs-template/blob/main/bridgetown-docs-template.gemspec#L16) and my guess is it's due to the package not existing in `npm`. As far as I can tell, it's not affecting anything though. No errors in the JS console at least...
